### PR TITLE
Reformatting examples in sections 6 and 7

### PR DESCRIPTION
**Pull request by jskeet**
This PR is as much to make sure we're agreed on stylistic changes as
much as anything else.

### CODE REVIEW

**Review by BillWagner — APPROVED** [review]
This LGTM @jskeet 

I agree with all the style changes you made.

Just to make sure: We agree on 4 spaces for indentation, correct?

**Comment by jskeet** [comment]
> Just to make sure: We agree on 4 spaces for indentation, correct?

The checks I ran earlier seems to think that would be fine in terms of Word conversion - where there are very long lines (above ~96 characters) there are almost always comments anyway, and we can move those.

**Comment by jskeet** [comment]
(Will just wait for Rex as well.)

**Review by Nigel-Ecma — APPROVED** [review]
What, no more games hiding and seeking the opening brace? 😢😉

**Review by RexJaeschke — APPROVED** [review]

**Comment by RexJaeschke** [comment]
@jskeet I wasn't listed as a reviewer, but your message suggested you were waiting on me, so I added myself and approved this.

**Comment by jskeet** [comment]
Whoops - thanks Rex. Yes, I misread the suggested reviewers.

**Pull request merged**
