### PR TITLE
Merge the latest draft-v8 into draft-v9

### PR DESCRIPTION
**Pull request by BillWagner**
We've been getting more work done.

DO NOT SQUASH THIS PR. WE WANT TO KEEP THE V8 HISTORY

### CODE REVIEW

**Comment by BillWagner** [comment]
Once this is merged, I'll create the PR to restore the `MemberNotNull` and `MemberNotNullWhen` attributes in C# 9

**Comment by jskeet** [comment]
Is there anything specific you want me to review about this?

**Comment by BillWagner** [comment]
> Is there anything specific you want me to review about this?

@jskeet Just a quick sanity check. There were no conflicts when I did the merges, so it should be fine.

**Review by jskeet — APPROVED** [review]
Nothing really obvious springs to mind, but I haven't done significant checking.

**Pull request merged**
