### PR TITLE
Fix bad link references

### PR DESCRIPTION
**Pull request by RexJaeschke**
In 4 places in 3 files, I'd written $ instead of § to introduce a link's destination for a link that did not yet exist.

I also fixed a code-fencing error.

### CODE REVIEW

**Review by BillWagner — APPROVED** [review]
This LGTM @RexJaeschke 

I'll :shipit: now.

**Comment by BillWagner** [comment]
@RexJaeschke I merged this, and expected to see a related PR that updates these links. That didn't happen. I think it's because the previous action had replaced the key `unmanaged-types-new-clause` with its section number.  

I'll make an issue for the section renumbering tool so that it flags an error in that case. In the meantime, what is the reference that should go in its place? Once I test my fixes in the section renumbering tool, I'll update the references.

**Comment by RexJaeschke** [comment]
@BillWagner (Hopefully) I just fixed this with PR #337. Clearly, I didn't thing this through before. By changing the $ to §, I naively figured the number-fixup tool would kick in and update that. However, when that was run on the original merge some time ago, it assigned that new section a number, so no new reconciliation was possible this time. It sure is hard to get good help nowadays!

**Comment by BillWagner** [comment]
@RexJaeschke Your naive plan helped me find a few errors in the number-fixup tool.  See #336, which I think makes #337 unnecessary (but also prevents those kinds of errors coming back).

**Pull request merged**
