### PR TITLE
[BULK UPDATE] DocuTune - Fix build validation issues: docs-link-absolute

### PR DESCRIPTION
**Pull request by alexbuckgit**
[BULK UPDATE] DocuTune - Fix build validation issues: docs-link-absolute

**Global effort to fix build validation errors**

The Content & Learning team is fixing build validation errors on docs.microsoft.com for the rest of H2. This will eliminate potential accessibility, security, and usability issues. This PR was generated using DocuTune. It includes only build validation fixes and does not change other content.

DocuTune PRs improve quality of technical content by finding and automatically correcting a broad set of issues only where the correction is suitable. Please review within five business days and merge or comment in the PR with any changes you'd like to see. Thank you!

CorrelationId: 0df9c2d6-63f8-4d1e-8b57-b33611a06514
InitiativeId: docutune-build-validation-issues-2022-05
PointOfContact: @MonicaRush

### CODE REVIEW

**Comment by alexbuckgit** [comment]
#docutune-draft

**Comment by KalleOlaviNiemitalo** [comment]
Are these admin files even published to docs.microsoft.com at all? I don't think they are; <https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/introduction> maps to <https://github.com/dotnet/csharpstandard/blob/draft-v7/standard/introduction.md> so there's no URL for an "admin" folder as a sibling of "standard". As such I think it's better to reject this PR so that the Markdown files rendered on GitHub have working links.

However, "en-us/" could be removed from the links so that they can open translated pages if available.

**Comment by BillWagner** [comment]
Hi @alexbuckgit 

None of these relative links will resolve correctly. This repo is a dependent repository for docs.microsoft.com.

The files in the /standard folder are the source for the C# draft standard folder. None of the files in the admin folder are published. Furthermore, the standard folder is the ECMA C# standard, and shouldn't link to any of the Microsoft docs files. None of the docutune work is necessary in this repo. 

I'm thinking that we should close this PR.

**Comment by alexbuckgit** [comment]
@KalleOlaviNiemitalo @BillWagner 

Thanks for the info! I'll close this PR and remove this repo from our working list.

#docutune-abandoned

**Pull request closed without merging**
