### PR TITLE
Clarify the introduction

### PR DESCRIPTION
**Pull request by kevinlu11**
Clarified the introduction while preserving all important and unique info.

### CODE REVIEW

**Comment by jskeet** [comment]
This looks *less* clear to me. What do you believe is clarified by this?

**Comment by kevinlu11** [comment]
> This looks _less_ clear to me. What do you believe is clarified by this?

The first time I read this doc, I had to wade through what in my view was a verbose and barely comprehensible paragraph before I even knew what a "documentation comment" in C# was. Keep in mind that I am NOT a C# expert, and that all of my knowledge of C# documentation comments came from reading this doc several hours ago. Therefore, I don't suffer from the "curse of knowledge" in this domain; I am in touch with the beginner's perspective.

I replaced that verbose paragraph with a single sentence (the first sentence in my edit) that I thought would be crystal clear, even for a beginner like myself. What about my edit seems unclear to you?

**Comment by kevinlu11** [comment]
(Well, okay, more like "half-paragraph", but still...)

**Comment by jskeet** [comment]
It loses a lot of information - for example what is expected of a conformant compiler. The standard isn't designed to be a beginner's guide - while obviously we should make it as clear as possible, it's *expected* to be verbose and detailed, in order to be as precise as possible.

Every individual sentence in the existing standard seems to be reasonably clear to me. Would just breaking the paragraph up help a bit?

**Comment by kevinlu11** [comment]
I thought all the info I removed was either mentioned later in the article, or clear from context. For example, I took the part about conforming compiler to be unnecessary if one knows that the comments are just ordinary comments, which should be clear from looking at their syntax (since each line starts with "//[...]")

**Comment by kevinlu11** [comment]
Also, the docstrings in the other languages I've seen (Rust, Python, Clojure) are just ordinary comments, so I figured that documentation comments being ordinary comments was a universal pattern that didn't need to be mentioned.

**Comment by jskeet** [comment]
> For example, I took the part about conforming compiler to be unnecessary if one knows that the comments are just ordinary comments, which should be clear from looking at their syntax (since each line starts with "//[...]")

No, it's definitely necessary - as the language certainly *could* require a conforming compiler to, for example, validate that all documentation comments are valid XML.

We'll see what other working group members think, but personally I would prefer not to merge this PR.

**Comment by kevinlu11** [comment]
Fair enough, I don't know much about compilers, so it could well be that my edit was overzealous there. Would it be better if the part about conforming compilers were added back in, but the rest remained as I edited it?

I think my frustration during my first read-through mainly came from not being sure what documentation comments do; I had to furrow my brow and re-read a few times before I even understood that their purpose, in a nutshell, is to help generate documentation files. As you say, specifications should be detailed, but I think introductions should give an immediate idea of the most important points, and details should come later. This particular article does not seem aimed at such an expert audience that I think my edit was inappropriate, except *possibly* for the part about compilers where I am admittedly out of my depth.

Just my opinions; didn't mean to be rude (in case I came across that way).

**Comment by jskeet** [comment]
We'll see what others think. Your edit removes definitions of other terms, too. It may be that what's really needed isn't a change to the existing text so much as the addition of an introductory paragraph.

I would say that the specification *in general* isn't a good place to start to learn about a particular topic - it's about the details rather than the fundamentals.

**Comment by RexJaeschke** [comment]
I agree with @jskeet. This text has remained unchanged from the first edition, published in 2002. I don't see the proposal as an improvement. A formal specification is *definitely* not the place to start learning about a subject.

**Comment by BillWagner** [comment]
I agree that we should close this PR for the standard.

@klu22 I have a question for you, based on your earlier comments:  How did you arrive at this content rather than [the C# language reference on docs.microsoft.com](https://learn.microsoft.com/dotnet/csharp/language-reference/xmldoc/). That explanation is meant for developers learning C#. I'd like to know how you landed here so we can do some SEO work to direct traffic better to each set of articles.

**Comment by kevinlu11** [comment]
> @klu22 I have a question for you, based on your earlier comments: How did you arrive at this content rather than [the C# language reference on docs.microsoft.com](https://learn.microsoft.com/dotnet/csharp/language-reference/xmldoc/). That explanation is meant for developers learning C#. I'd like to know how you landed here so we can do some SEO work to direct traffic better to each set of articles.

I'm glad you asked! When I search "C# Documentation Comments", both DuckDuckGo and Google return this content as the first result, followed by links to either third-party (non-Microsoft) sources or to other Microsoft links titled something like "XML documentation comments[....]". Ironically, the addition of "XML" in those titles led me to believe that non-XML documentation comments also exist, so I thought "Okay, I should read about documentation comments in general before reading about the special XML ones." Of course, I now know that all documentation comments use XML. 

In contrast to those pages' titles, this page's title begins simply with "Documentation Comments [...]" which led me to believe this was the place to start learning about them. Since it's the first search result, too, I figured it must be a popular reference--perfect for beginners!

(After realizing my confusion, I went to the tutorial page and removed the confusing "XML" from its title, as you saw: https://github.com/dotnet/docs/pull/33055/commits)

Here's a pic of my DuckDuckGo search results, pre-title-edit:
Capture7

**Pull request closed without merging**
