### PR TITLE
A Typo fix update in expressions.md file

### PR DESCRIPTION
**Pull request by ermancetin**
It should be `as` in the text "... unlike the cast operator the `a` operator is not dynamically bound ..."

### CODE REVIEW

**Comment by ermancetin** [comment]
@dotnet-policy-service agree

**Review by jskeet — APPROVED** [review]
(Will let the CLA bot do its thing of course, but the change LGTM.)

**Comment by BillWagner** [comment]
closing and reopening for a fresh build.

**Comment by BillWagner** [comment]
This PR targets the V6 version of the standard.

@jskeet Do we want to update that version, or should we re-target this PR for v7? 

(If we merge this in V6, we should cherry-pick the commit into V7)

**Comment by jskeet** [comment]
@BillWagner: Given the release schedule, I suggest we retarget it to v7.

**Review by ugursabirer — APPROVED** [review]

**Review by ugursabirer — APPROVED** [review]

**Pull request merged**
