### PR TITLE
Revise Example Metadata User Guide

### PR DESCRIPTION
**Pull request by RexJaeschke**
Let this sit as DRAFT, as I may well have more edits to make soon.

### CODE REVIEW

**Comment by BillWagner** [comment]
@RexJaeschke 

Should this Pr be updated to target the `draft-v8` branch?

**Comment by RexJaeschke** [comment]
@BillWagner Yes please!

**Comment by RexJaeschke** [comment]
@BillWagner  Let's also take it out of Draft status and merge it.

**Review by BillWagner — APPROVED** [review]
This all LGTM @RexJaeschke 

I'll :shipit: now.

**Pull request merged**
