### PR TITLE
Fix ANTLR representation of The try statement

### PR DESCRIPTION
**Pull request by neNerower**
Fixes the problem described in issue #586.

### CODE REVIEW

**Review by Nigel-Ecma — APPROVED** [review]
@neNerower – Thanks for spotting this!

**Comment by neNerower** [comment]
@Nigel-Ecma 
I'm glad I can help improve your product !

**Comment by BillWagner** [comment]
ping @jskeet I'm happy to merge this. Do you want to take a look first?

**Comment by jskeet** [comment]
I'll have a look in the morning (UK)

**Review by jskeet — APPROVED** [review]

**Pull request merged**
