### PR TITLE
Clarify task types

### LINKED ISSUE #854: C# 7.x §15.15.1 must special-case Task and Task<TResult> because they lack AsyncMethodBuilderAttribute
**Describe the bug**

In the C# 7.x draft, §15.15.1 (Async functions / General) states:

> The *return_type* of an async method shall be either `void` or a ***task type***. For an async method that returns a value, a task type shall be generic. For an async method that does not return a value, a task type shall not be generic. Such types are referred to in this specification as `«TaskType»<T>` and `«TaskType»`, respectively. (The Standard library type `System.Threading.Tasks.Task` and types constructed from `System.Threading.Tasks.Task<TResult>` are task types.)
> A task type shall be a class or struct type that is associated with a ***task builder type*** via the attribute `System.Runtime.CompilerServices.AsyncMethodBuilderAttribute`. Such types are referred to in this specification as `«TaskBuilderType»<T>` and `«TaskBuilderType»`.

However, `System.Threading.Tasks.Task` and `System.Threading.Tasks.Task<TResult>` are not decorated with AsyncMethodBuilderAttribute. Not in §C.3 (Standard Library Types not defined in ISO/IEC 23271), and not in .NET Framework either.

**Example**

None.

**Expected behavior**

Special-case `System.Threading.Tasks.Task` and `System.Threading.Tasks.Task<TResult>` so that they need not be decorated with AsyncMethodBuilderAttribute.

**Additional context**

None.

### PR DESCRIPTION
**Pull request by jskeet**
- `Task` and `Task<T>` are classified as task types despite not specifying builder types
- Interfaces are allowed to be task types
- Enums and methods are prohibited from being decorated with AsyncMethodBuilderAttribute
- Task types must not be generic in more than one type parameter (including in terms of containing types)

Discussion required for all of this, but if merged, would fix #854, #856, #858 and #859.

### CODE REVIEW

**Comment by jskeet** [comment]
cc @KalleOlaviNiemitalo for thoughts

@BillWagner I figure we can probably get this hammered into better shape between ourselves (I'm not entirely happy with the way the generic restriction is expressed) and then get broader review.

**Comment by KalleOlaviNiemitalo** [comment]
> Task types must not be generic in more than one type parameter (including in terms of containing types)

That is not right.  Type arguments of types that contain the task type should be ignored; Outer\<char, int>.Inner\<long> should be allowed as a task type if it has the correct attribute.  But not as a task builder type.

**Comment by jskeet** [comment]
> That is not right. Type arguments of types that contain the task type should be ignored; `Outer<char, int>.Inner<long>` should be allowed as a task type if it has the correct attribute. But not as a task builder type.

That would certainly be simpler to specify. Can I ask what your reasoning is here? I suspect it's more advanced than mine... and we should probably have a note to explain either way.

**Comment by KalleOlaviNiemitalo** [comment]
Or is the idea that, if the task type is nested in a generic type, then the task builder type would not be able to have a Task property with the correct type, unless it hardcodes the type arguments of the containing type?  So that allowing such task types would not be useful in practice.  Which would then make the Roslyn behaviour an extension.

**Comment by jskeet** [comment]
> Or is the idea that, if the task type is nested in a generic type, then the task builder type would not be able to have a Task property with the correct type, unless it hardcodes the type arguments of the containing type? So that allowing such task types would not be useful in practice. Which would then make the Roslyn behaviour an extension.

That was my thinking, I think - but I feel like I'm still wading through cotton wool trying to think about this. I'm definitely not feeling like we should be bound by exactly what Roslyn allows, but I'm open to useful justifications.

**Comment by jskeet** [comment]
I've added another commit to basically copy the existing text from 15.15.2 (for task builders) and make it apply to task types.
This may be more restrictive than is strictly required (and Roslyn can allow a little more leeway), but I think it's a good starting point.

**Comment by jskeet** [comment]
I need to go back and reapply changes from #846 to this...

**Comment by jskeet** [comment]
Oops - no, I *don't* need to reapply changes from #846. It's all fine; @BillWagner does this look ready to merge?

**Review by BillWagner — APPROVED** [review]
This LGTM @jskeet 

Let's :shipit:

**Pull request merged**
