### PR TITLE
Fix tables in lists

### PR DESCRIPTION
**Pull request by jskeet**
This is now ready for review.

### CODE REVIEW

**Comment by jskeet** [comment]
Fixes #441.

**Comment by jskeet** [comment]
Note: we should validate what happens to 11.9.6 when both this and #515 are merged (that's got an example in a triply-nested list). I hope it'll be okay, but it's worth checking.

**Review by BillWagner — APPROVED** [review]
This LGTM @jskeet 

Let's :shipit:

**Comment by jskeet** [comment]
Thanks - will rebase #515 on this, as it's very likely to have merge conflicts.

**Pull request merged**
