### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by pkulikov**
By the way, what does this sentence mean? Is it somehow related to the `dynamic` type or "dynamic" is used with another meaning here?

### CODE REVIEW

**Comment by KalleOlaviNiemitalo** [comment]
Yes I think it means the `dynamic` type.

```csharp
using System;

public class B {
    #if false
    protected static void Mem(int i) {
        Console.WriteLine("B.Mem(int)");
    }
    #endif
        
    protected static void Mem(long l) {
        Console.WriteLine("B.Mem(long)");
    }
}

public class D : B {
    static readonly dynamic d = 1;
    
    static void Main() {
        // Resolves to the Loc(int) local function
        // at compile time.  Does an implicit conversion
        // from dynamic to int and calls that.
        Loc(d);
       
        // Does tbe same as above.
        int i = d;
        Loc(i);
        
        // Resolves to some accessible Mem at run time.
        // If class B is defined in a different assembly
        // and a new version is installed that adds Mem(int),
        // then this starts choosing that instead of
        // Mem(long), even if Mem(int) did not exist at
        // compile time.
        Mem(d);
        
        void Loc(int i) {}
    }
}
```

**Review by Nigel-Ecma — CHANGES_REQUESTED** [review]
Grammatically “runtime”, “run-time” and ”run time” are interchangeable and consistency of choice is suggested.

The Standard primarily uses “run-time”, “runtime” is the second choice (I would have expected these two to be the other way around), and “run time” never seems to appear.

On that basis this PR should be closed as “no change required”. Another PR could be raised to address the lack of consistency.

[Tagged "Request changes" as Github seems to lack a “Close” option.]

**Comment by Nigel-Ecma** [comment]
@pkulikov – regarding “dynamic” @KalleOlaviNiemitalo is correct, it means dynamic type. As a non American-English speaker I might have added a few words if I was writing it, but to me its very American-English ;-) and not worth changing.

**Comment by Nigel-Ecma** [comment]
Ah, I see I should have just commented and not reviewed, hitting the Close button…

**Comment by Nigel-Ecma** [comment]
…but it hasn't closed, I've confused Github again :-)

**Comment by jskeet** [comment]
Actually closing :)

**Comment by pkulikov** [comment]
@jskeet @Nigel-Ecma why is this PR closed? Usually, opposite of "compile time" is "run time" (with space) not "runtime" (without space). Or spec really means CLR by "runtime"?

I'm sorry if my in-PR question mislead you.

[Update: I've noticed the motivation later.]

**Comment by pkulikov** [comment]
> Grammatically “runtime”, “run-time” and ”run time” are interchangeable and consistency of choice is suggested.

I've got used that in .NET docs "runtime" refers to CLR. That is different from "run time", which is time when the code is executed (by runtime). So, I wouldn't say these two are interchangeable. And as many readers of Standard come from .NET docs (I assume), the language spec may be misleading and confusing to them (one example is me).

However, I see that the style guide has changed since some time ago and uses one word to mean different things:
https://learn.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/r/runtime

That's unfortunate.

**Comment by pkulikov** [comment]
@KalleOlaviNiemitalo thank you for the example

**Pull request closed without merging**
