### PR TITLE
Fix ANTLR representation of Fixed-size buffer declarations

### PR DESCRIPTION
**Pull request by neNerower**
Fixes the problem described in issue #583.

### CODE REVIEW

**Review by Nigel-Ecma — APPROVED** [review]
@neNerower – Again thanks!

**Comment by BillWagner** [comment]
ping @jskeet I'm happy merging this. Do you want to take a look

**Comment by jskeet** [comment]
If Nigel's happy, I'm happy - I don't know ANTLR well enough to know whether introducing a new rule is better or worse than inlining it.

**Comment by neNerower** [comment]
@jskeet 
It's not about changing the style, but about fixing the inaccuracy of the grammar, which made it possible to interpret incorrect statements as valid.
Nigel is aware of all the details, you can also find more information in issue #583.

**Comment by jskeet** [comment]
I understand the change was semantic as well - but I assume it *could* have been done inline as well. I'm fine either way.

**Pull request merged**
