### PR TITLE
Update note spacing

### PR DESCRIPTION
**Pull request by BillWagner**
Remove blank lines between numbered items in the list.
Where a blank line is needed, add `> ` to make a new paragraph in the same note.

### CODE REVIEW

**Comment by jskeet** [comment]
When I tried doing something very similar last night, the Word converter broke entirely... but yes, we need to sort it out.

**Comment by BillWagner** [comment]
I'll try to spend some time in the Word Converter to see if I can get the right output. It will be a good first change to learn the codebase more.

**Comment by jskeet** [comment]
I think this is now redundant due to https://github.com/dotnet/csharpstandard/pull/509/commits/32ffffe7e04c7a355add291d0c1e720beddd2234.

**Comment by BillWagner** [comment]
closing as this is now redundant.

**Pull request closed without merging**
