### PR TITLE
Update v7 feature tracker

### PR DESCRIPTION
**Pull request by RexJaeschke**
Updated some PR numbers, and added links to the MS proposals.

### CODE REVIEW

**Comment by RexJaeschke** [comment]
@jskeet This still-unapproved PR seems to have slipped through the cracks. Since then, PR 570 was raised and closed, and that changes the V7 feature tracker contents. What we really needed is for 570 to be applied *after* this PR.

**Comment by BillWagner** [comment]
@RexJaeschke 

Looking at the conflicts, I think I can resolve them, with a bit of guidance from you. This PR adds links to all the MS feature specs in the 2nd column. The PR (and rightmost) columns have often been updated in PR #570 

Is that correct? If so, I'll go ahead and resolve the conflicts in place.

**Comment by RexJaeschke** [comment]
@BillWagner Almost all the changes in this PR add a link to the MS proposal. The few other changes should also be preserved.

**Comment by BillWagner** [comment]
@RexJaeschke I did the merge, and I think I caught everything correctly.

**Comment by RexJaeschke** [comment]
LGTM, @BillWagner. I made you the reviewer instead, so go ahead and merge.

**Review by BillWagner — APPROVED** [review]
LGTM

**Pull request merged**
