### PR TITLE
Remove markdown lint from the end of notes/examples

### PR DESCRIPTION
**Pull request by jskeet**

### CODE REVIEW

**Comment by BillWagner** [comment]
There is one failing test now. Is that a false positive?

**Comment by jskeet** [comment]
Ooh, no... that's odd. I'm out of time for today, but I'll look first thing tomorrow.

**Comment by jskeet** [comment]
Ah - it's possible that this is a "difference between \r\n and \n" issue. That's just a guess though; will look into it properly tomorrow.

**Comment by jskeet** [comment]
@BillWagner: Fixed now - it's an annoyance of the Markdown parser that even if we normalize the input, it then uses `Environment.NewLine` itself. I've amended the commit, and the test is now passing.

**Review by BillWagner — COMMENTED** [review]
Thanks @jskeet 

This LGTM. Let's :shipit:

**Review by BillWagner — APPROVED** [review]

**Pull request merged**
